# Generated by Django 5.1.2 on 2025-08-20 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Apple Store', max_length=255)),
                ('store_description', models.TextField(default='Your trusted destination for the latest Apple products')),
                ('store_email', models.EmailField(default='contact@applestore.com', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('store_phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('CAD', 'CAD - Canadian Dollar')], default='USD', max_length=3)),
                ('timezone', models.CharField(choices=[('America/New_York', 'Eastern Time'), ('America/Chicago', 'Central Time'), ('America/Denver', 'Mountain Time'), ('America/Los_Angeles', 'Pacific Time')], default='America/New_York', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('order_notifications', models.BooleanField(default=True)),
                ('inventory_alerts', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_guest_checkout', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
